### ISSUE TITLE
Invalid AppId?

### ISSUE THREAD

**Issue by valdr** [MycroftAI/fallback-wolfram-alpha#1]
As I noticed the Wolfram Alpha skill was blacklisted, and a "fallback"-version was available, I installed it.
Asking "what is 2 times 2" gets me this error, and no "4":

```
- DEBUG - {"type": "recognizer_loop:utterance", "data": {"lang": "en-us", "utterances": ["what is 2 times 2"]}, "context": null}
mycroft.skills.intent_service - ERROR -
Traceback (most recent call last):
File "/home/bokkie/programming/Github/MyCroft/mycroft-core/mycroft/skills/intent_service.py", line 239, in handle_utterance
context_manager=self.context_manager))
StopIteration
- DEBUG - {"type": "intent_failure", "data": {"lang": "en-us", "utterance": "what is 2 times 2"}, "context": null}
mycroft.skills.padatious_service - DEBUG - Padatious fallback attempt: what is 2 times 2
mycroft.skills.core - INFO - Exception in fallback: max() arg is an empty sequence
fallback-wolfram-alpha__init__ - DEBUG - WolframAlpha fallback attempt: what is 2 times 2
fallback-wolfram-alpha__init__ - DEBUG - Falling back to WolframAlpha: what is 2 times 2
Display Manager (mycroft.client.enclosure) - DEBUG - Setting active skill to WolframAlphaSkill
- DEBUG - {"type": "enclosure.mouth.think", "data": {}, "context": null}
requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/wa?input=what+is+2+times+2 HTTP/1.1" 200 417
fallback-wolfram-alpha__init__ - ERROR - Error 1: Invalid appid
Traceback (most recent call last):
File "/opt/mycroft/skills/fallback-wolfram-alpha/__init__.py", line 156, in handle_fallback
res = self.client.query(query)
File "/opt/mycroft/skills/fallback-wolfram-alpha/__init__.py", line 82, in query
return wolframalpha.Result(StringIO(data.content))
File "/home/bokkie/.virtualenvs/mycroft/local/lib/python2.7/site-packages/wolframalpha/__init__.py", line 178, in __init__
super(Result, self).__init__(doc)
File "/home/bokkie/.virtualenvs/mycroft/local/lib/python2.7/site-packages/wolframalpha/__init__.py", line 62, in __init__
self._handle_error()
File "/home/bokkie/.virtualenvs/mycroft/local/lib/python2.7/site-packages/wolframalpha/__init__.py", line 69, in _handle_error
raise Exception(template.format(**self))
Exception: Error 1: Invalid appid
mycroft.skills.core - WARNING - No fallback could handle intent.
```

**Comment by penrods** [comment]
We were still working with Wolfram on getting our official accounts setup.  Should work for you now.  I'll close, but we can reopen if you still see issues.
